// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitConversion.Data;

#nullable disable

namespace UnitConversion.Data.Migrations
{
    [DbContext(typeof(UnitConversionContext))]
    partial class UnitConversionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnitConversion.Models.Data.ConversionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Input")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Output")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SourceUnitId")
                        .HasColumnType("int");

                    b.Property<int>("TargetUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConversionHistory");
                });

            modelBuilder.Entity("UnitConversion.Models.Data.ConversionRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceUnitId")
                        .HasColumnType("int");

                    b.Property<int>("TargetUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConversionRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Formula = "(inputVal*1000)",
                            SourceUnitId = 1,
                            TargetUnitId = 2
                        },
                        new
                        {
                            Id = 2,
                            Formula = "(inputVal*100000)",
                            SourceUnitId = 1,
                            TargetUnitId = 3
                        },
                        new
                        {
                            Id = 3,
                            Formula = "(inputVal/1.609)",
                            SourceUnitId = 1,
                            TargetUnitId = 4
                        },
                        new
                        {
                            Id = 4,
                            Formula = "(inputVal*3281)",
                            SourceUnitId = 1,
                            TargetUnitId = 5
                        },
                        new
                        {
                            Id = 5,
                            Formula = "(inputVal/39370)",
                            SourceUnitId = 1,
                            TargetUnitId = 6
                        },
                        new
                        {
                            Id = 6,
                            Formula = "(inputVal/1000)",
                            SourceUnitId = 2,
                            TargetUnitId = 1
                        },
                        new
                        {
                            Id = 7,
                            Formula = "(inputVal*100)",
                            SourceUnitId = 2,
                            TargetUnitId = 3
                        },
                        new
                        {
                            Id = 8,
                            Formula = "(inputVal/1609)",
                            SourceUnitId = 2,
                            TargetUnitId = 4
                        },
                        new
                        {
                            Id = 9,
                            Formula = "(inputVal*3.281)",
                            SourceUnitId = 2,
                            TargetUnitId = 5
                        },
                        new
                        {
                            Id = 10,
                            Formula = "(inputVal*39.37)",
                            SourceUnitId = 2,
                            TargetUnitId = 6
                        },
                        new
                        {
                            Id = 11,
                            Formula = "(inputVal/100000)",
                            SourceUnitId = 3,
                            TargetUnitId = 1
                        },
                        new
                        {
                            Id = 12,
                            Formula = "(inputVal/100)",
                            SourceUnitId = 3,
                            TargetUnitId = 2
                        },
                        new
                        {
                            Id = 13,
                            Formula = "(inputVal/160900)",
                            SourceUnitId = 3,
                            TargetUnitId = 4
                        },
                        new
                        {
                            Id = 14,
                            Formula = "(inputVal/30.48)",
                            SourceUnitId = 3,
                            TargetUnitId = 5
                        },
                        new
                        {
                            Id = 15,
                            Formula = "(inputVal/2.54)",
                            SourceUnitId = 3,
                            TargetUnitId = 6
                        },
                        new
                        {
                            Id = 16,
                            Formula = "(inputVal*1.609)",
                            SourceUnitId = 4,
                            TargetUnitId = 1
                        },
                        new
                        {
                            Id = 17,
                            Formula = "(inputVal*1609)",
                            SourceUnitId = 4,
                            TargetUnitId = 2
                        },
                        new
                        {
                            Id = 18,
                            Formula = "(inputVal*160900)",
                            SourceUnitId = 4,
                            TargetUnitId = 3
                        },
                        new
                        {
                            Id = 19,
                            Formula = "(inputVal*5280)",
                            SourceUnitId = 4,
                            TargetUnitId = 5
                        },
                        new
                        {
                            Id = 20,
                            Formula = "(inputVal*63360)",
                            SourceUnitId = 4,
                            TargetUnitId = 6
                        },
                        new
                        {
                            Id = 21,
                            Formula = "(inputVal/3281)",
                            SourceUnitId = 5,
                            TargetUnitId = 1
                        },
                        new
                        {
                            Id = 22,
                            Formula = "(inputVal/3.281)",
                            SourceUnitId = 5,
                            TargetUnitId = 2
                        },
                        new
                        {
                            Id = 23,
                            Formula = "(inputVal*30.48)",
                            SourceUnitId = 5,
                            TargetUnitId = 3
                        },
                        new
                        {
                            Id = 24,
                            Formula = "(inputVal/5280)",
                            SourceUnitId = 5,
                            TargetUnitId = 4
                        },
                        new
                        {
                            Id = 25,
                            Formula = "(inputVal*12)",
                            SourceUnitId = 5,
                            TargetUnitId = 6
                        },
                        new
                        {
                            Id = 26,
                            Formula = "(inputVal/39370)",
                            SourceUnitId = 6,
                            TargetUnitId = 1
                        },
                        new
                        {
                            Id = 27,
                            Formula = "(inputVal/39.37)",
                            SourceUnitId = 6,
                            TargetUnitId = 2
                        },
                        new
                        {
                            Id = 28,
                            Formula = "(inputVal* 2.54)",
                            SourceUnitId = 6,
                            TargetUnitId = 3
                        },
                        new
                        {
                            Id = 29,
                            Formula = "(inputVal/63360)",
                            SourceUnitId = 6,
                            TargetUnitId = 4
                        },
                        new
                        {
                            Id = 30,
                            Formula = "(inputVal/12)",
                            SourceUnitId = 6,
                            TargetUnitId = 5
                        },
                        new
                        {
                            Id = 31,
                            Formula = "(inputVal/1000)",
                            SourceUnitId = 7,
                            TargetUnitId = 8
                        },
                        new
                        {
                            Id = 32,
                            Formula = "(inputVal*1000)",
                            SourceUnitId = 7,
                            TargetUnitId = 9
                        },
                        new
                        {
                            Id = 33,
                            Formula = "(inputVal/453.6)",
                            SourceUnitId = 7,
                            TargetUnitId = 10
                        },
                        new
                        {
                            Id = 34,
                            Formula = "(inputVal*1000)",
                            SourceUnitId = 8,
                            TargetUnitId = 7
                        },
                        new
                        {
                            Id = 35,
                            Formula = "(inputVal*1e+6)",
                            SourceUnitId = 8,
                            TargetUnitId = 9
                        },
                        new
                        {
                            Id = 36,
                            Formula = "(inputVal*2.205)",
                            SourceUnitId = 8,
                            TargetUnitId = 10
                        },
                        new
                        {
                            Id = 37,
                            Formula = "(inputVal/1000)",
                            SourceUnitId = 9,
                            TargetUnitId = 7
                        },
                        new
                        {
                            Id = 38,
                            Formula = "(inputVal/1e+6)",
                            SourceUnitId = 9,
                            TargetUnitId = 8
                        },
                        new
                        {
                            Id = 39,
                            Formula = "(inputVal/453600)",
                            SourceUnitId = 9,
                            TargetUnitId = 10
                        },
                        new
                        {
                            Id = 40,
                            Formula = "(inputVal*453.6)",
                            SourceUnitId = 10,
                            TargetUnitId = 7
                        },
                        new
                        {
                            Id = 41,
                            Formula = "(inputVal/2.205)",
                            SourceUnitId = 10,
                            TargetUnitId = 8
                        },
                        new
                        {
                            Id = 42,
                            Formula = "(inputVal*453600)",
                            SourceUnitId = 10,
                            TargetUnitId = 9
                        },
                        new
                        {
                            Id = 43,
                            Formula = "(inputVal+ 273.15)",
                            SourceUnitId = 11,
                            TargetUnitId = 12
                        },
                        new
                        {
                            Id = 44,
                            Formula = "((inputVal*9/5) + 32)",
                            SourceUnitId = 11,
                            TargetUnitId = 13
                        },
                        new
                        {
                            Id = 45,
                            Formula = "(inputVal− 273.15)",
                            SourceUnitId = 12,
                            TargetUnitId = 11
                        },
                        new
                        {
                            Id = 46,
                            Formula = "((inputVal− 273.15)*9/5) + 32)",
                            SourceUnitId = 12,
                            TargetUnitId = 13
                        },
                        new
                        {
                            Id = 47,
                            Formula = "((inputVal-32)*5/9)",
                            SourceUnitId = 13,
                            TargetUnitId = 11
                        },
                        new
                        {
                            Id = 48,
                            Formula = "((inputVal-32)*5/9 +273.15)",
                            SourceUnitId = 13,
                            TargetUnitId = 12
                        });
                });

            modelBuilder.Entity("UnitConversion.Models.Data.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1500),
                            Name = "Kilometer",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1513),
                            Name = "Meter",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1514),
                            Name = "Centimeter",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1515),
                            Name = "Mile",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1516),
                            Name = "Foot",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1517),
                            Name = "Inch",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1518),
                            Name = "Gram",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1519),
                            Name = "Kilogram",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1520),
                            Name = "Miligram",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1521),
                            Name = "Pound",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1522),
                            Name = "Celsius",
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1523),
                            Name = "Kelvin",
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 10, 6, 13, 50, 32, 812, DateTimeKind.Local).AddTicks(1524),
                            Name = "Fahrenheit",
                            Type = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
